@echo off

IF NOT EXIST bin mkdir bin

SET EXECUTABLE=pacman.exe
SET COMMON_DEFINES=/DUNICODE /D_UNICODE /D_CRT_SECURE_NO_WARNINGS
SET COMMON_COMPILERFLAGS=/W4 /wd4204 /wd4200 /wd4201 /FC /Fe:%EXECUTABLE%
SET LINKERFLAGS=/link /INCREMENTAL:NO /SUBSYSTEM:WINDOWS
SET LIBRARIES=kernel32.lib user32.lib gdi32.lib opengl32.lib

if "%1" == "RELEASE" (
    SET DEFINES=/DNDEBUG /D_NDEBUG
    SET COMPILERFLAGS=/nologo /O2 /MT
) else (
    SET DEFINES=/DDEBUG /D_DEBUG
    SET COMPILERFLAGS=/nologo /Od /MTd /Zi
)

pushd bin

cl %DEFINES% %COMMON_DEFINES% %COMPILERFLAGS% %COMMON_COMPILERFLAGS% ..\src\win\win_pacman.c %LIBRARIES% %LINKERFLAGS%

copy /b /y %EXECUTABLE% ..\

popd
