/*
 * Pacman Clone
 *
 * Copyright (c) 2021 Amanch Esmailzadeh
 */

#ifndef GL_FUNCS_H
#define GL_FUNCS_H

#include <assert.h>

#ifdef _WIN32

#include <gl/gl.h>
#include "extern/wglext.h"
PFNWGLCHOOSEPIXELFORMATARBPROC wglChoosePixelFormatARB;
PFNWGLCREATECONTEXTATTRIBSARBPROC wglCreateContextAttribsARB;
PFNWGLSWAPINTERVALEXTPROC wglSwapIntervalEXT;

#define GL_GET_PROC_ADDRESS wglGetProcAddress

#endif

#include "extern/glext.h"

PFNGLCREATEPROGRAMPROC glCreateProgram;
PFNGLCREATESHADERPROC glCreateShader;
PFNGLSHADERSOURCEPROC glShaderSource;
PFNGLCOMPILESHADERPROC glCompileShader;
PFNGLATTACHSHADERPROC glAttachShader;
PFNGLLINKPROGRAMPROC glLinkProgram;
PFNGLUSEPROGRAMPROC glUseProgram;
PFNGLDETACHSHADERPROC glDetachShader;
PFNGLDELETESHADERPROC glDeleteShader;
PFNGLGENVERTEXARRAYSPROC glGenVertexArrays;
PFNGLBINDVERTEXARRAYPROC glBindVertexArray;
PFNGLGENBUFFERSPROC glGenBuffers;
PFNGLBINDBUFFERPROC glBindBuffer;
PFNGLBUFFERDATAPROC glBufferData;
PFNGLENABLEVERTEXATTRIBARRAYPROC glEnableVertexAttribArray;
PFNGLVERTEXATTRIBPOINTERPROC glVertexAttribPointer;
PFNGLGETSHADERIVPROC glGetShaderiv;
PFNGLGETSHADERINFOLOGPROC glGetShaderInfoLog;
PFNGLGETPROGRAMIVPROC glGetProgramiv;
PFNGLGETPROGRAMINFOLOGPROC glGetProgramInfoLog;
PFNGLACTIVETEXTUREPROC glActiveTexture;

void load_all_gl_extensions(void) {
#define LOAD_GL_EXTENSION(type, func) \
    do { \
        func = (type)GL_GET_PROC_ADDRESS(#func); \
        assert(func); \
    } while(0)

#ifdef _WIN32
    LOAD_GL_EXTENSION(PFNWGLCHOOSEPIXELFORMATARBPROC, wglChoosePixelFormatARB);
    LOAD_GL_EXTENSION(PFNWGLCREATECONTEXTATTRIBSARBPROC, wglCreateContextAttribsARB);
    LOAD_GL_EXTENSION(PFNWGLSWAPINTERVALEXTPROC, wglSwapIntervalEXT);
#endif

    LOAD_GL_EXTENSION(PFNGLCREATEPROGRAMPROC, glCreateProgram);
    LOAD_GL_EXTENSION(PFNGLCREATESHADERPROC, glCreateShader);
    LOAD_GL_EXTENSION(PFNGLSHADERSOURCEPROC, glShaderSource);
    LOAD_GL_EXTENSION(PFNGLCOMPILESHADERPROC, glCompileShader);
    LOAD_GL_EXTENSION(PFNGLATTACHSHADERPROC, glAttachShader);
    LOAD_GL_EXTENSION(PFNGLLINKPROGRAMPROC, glLinkProgram);
    LOAD_GL_EXTENSION(PFNGLUSEPROGRAMPROC, glUseProgram);
    LOAD_GL_EXTENSION(PFNGLDETACHSHADERPROC, glDetachShader);
    LOAD_GL_EXTENSION(PFNGLDELETESHADERPROC, glDeleteShader);
    LOAD_GL_EXTENSION(PFNGLGENVERTEXARRAYSPROC, glGenVertexArrays);
    LOAD_GL_EXTENSION(PFNGLBINDVERTEXARRAYPROC, glBindVertexArray);
    LOAD_GL_EXTENSION(PFNGLGENBUFFERSPROC, glGenBuffers);
    LOAD_GL_EXTENSION(PFNGLBINDBUFFERPROC, glBindBuffer);
    LOAD_GL_EXTENSION(PFNGLBUFFERDATAPROC, glBufferData);
    LOAD_GL_EXTENSION(PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray);
    LOAD_GL_EXTENSION(PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer);
    LOAD_GL_EXTENSION(PFNGLGETSHADERIVPROC, glGetShaderiv);
    LOAD_GL_EXTENSION(PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog);
    LOAD_GL_EXTENSION(PFNGLGETPROGRAMIVPROC, glGetProgramiv);
    LOAD_GL_EXTENSION(PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog);
    LOAD_GL_EXTENSION(PFNGLACTIVETEXTUREPROC, glActiveTexture);

#undef LOAD_GL_EXTENSION
}

#endif /* GL_FUNCS_H */
